version: '3'

services:
  web:
    build: .
    restart: always
    container_name: music_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - database.env
    volumes:
      - .:/var/www/html/djangomusicapp
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
    container_name: music_db
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"